services:
  backend:
    image: cosmtrek/air:latest
    working_dir: /app
    volumes:
      - ./backend:/app
      - go-modules:/go/pkg/mod
    environment:
      - IS_DEV=true

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "yarn install && yarn dev"
    volumes:
      - ./frontend:/app
      - node-modules:/app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}

volumes:
  go-modules:
  node-modules:
